'use client'
import { Inter } from "next/font/google";
import Header from "./component/header/page";
import Footer from "./component/footer/page";
import { useRouter } from "next/navigation";
import { usePathname } from "next/navigation";
import { useParams } from "next/navigation";
import "./globals.css";
import "./Addon.css"
const inter = Inter({ subsets: ["latin"] });

//export const metadata = {
  //title: "Create Next App",
  //description: "Generated by create next app",
//};

export default function RootLayout({children}) {
  
  let router = useRouter();
  let params = useParams();
  let pathname = usePathname();
  if(pathname === "/project/ACLEDAclone"){
    return (
      <html lang="en">  
        <body>
        <div>{children}</div>
          </body>
      </html>
    );
  }
  else if(pathname === "/project/Calculator"){
    return (
      <html lang="en">  
        <body>
        <div>{children}</div>
          </body>
      </html>
    );
  }
  else if(pathname === "/project/Pickgame"){
    return (
      <html lang="en">  
        <body>
        <div>{children}</div>
          </body>
      </html>
    );
  }
  else if(pathname === "/project/Servicewebsite"){
    return (
      <html lang="en">  
        <body>
        <div>{children}</div>
          </body>
      </html>
    );
  }
  else{

  return (
    <html lang="en">
      
      <body className='Home-body'>
      <div className="header-layout" >
        <Header></Header>
        </div>
      <div className="children-layout" >{children}</div>
      <div className="footer-layout" ><Footer></Footer></div>
        
        
        
        </body>
      
    </html>
  );
}
}
